version: "3.8"

services:
  app:
    image: itsraghav/demo-app:latest
    expose:
      - 3000
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

